version: '3'

networks:
  traefik:
    external: true

services:
  traefik:
    images: traefik
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '8090:8080'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './traefik.yml:/etc/traefik/traefik.yml'
      - './acme.json:/etc/traefik/acme.json'
      - './logs:/var/log/traefik'
    networks:
      - 'traefik'
