version: "3.3"

networks:
  traefik:
    external: true

volumes:
  GRAFANA:
  INFLUXDB:
  CHRONOGRAF:

services:
  influxdb:
    build: influxdb_dockerfile/.
    image: eminent/influxdb:latest
    container_name: influxdb
    volumes:
      - INFLUXDB:/var/lib/influxdb
    networks:
      - traefik
    ports:
      - '8086:8086'
    env_file:
      - ./.env
   labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.influxdb.rule=(`influxdb.mon.local`)"
      - "traefik.http.routers.influxdb.entrypoints=web"
      - "traefik.http.services.influxdb.loadbalancer.server.port=8086"
      - "traefik.http.services.influxdb.loadbalancer.server.scheme=http"
      - "traefik.http.services.influxdb.loadbalancer.passHostHeader=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
  chronograf:
    build: chronograf_dockerfile/.
    image: eminent/chronograf
    container_name: chronograf
    volumes:
      - CHRONOGRAF:/var/lib/chronograf
    networks:
      - traefik
    ports:
      - '127.0.0.1:8888:8888'
    depends_on:
      - influxdb
    env_file:
      - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.cronograf.rule=(`cronofrag.mon.local`)"
      - "traefik.http.routers.cronograf.entrypoints=web"
      - "traefik.http.services.chronograf.loadbalancer.server.port=8888"
      - "traefik.http.services.chronograf.loadbalancer.server.scheme=http"
      - "traefik.http.services.chronograf.loadbalancer.passHostHeader=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
  grafana:
    build: grafana_dockerfile/. 
    image: eminent/grafana:latest
    container_name: grafana
    restart: always
    volumes:
      - GRAFANA:/var/lib/grafana
    networks:
      - traefik
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.grafana.rule=(`grafna.mon.local`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.services.grafana.loadbalancer.server.scheme=http"
      - "traefik.http.services.grafana.loadbalancer.passHostHeader=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
