
FROM grafana/grafana:latest

RUN grafana-cli plugins install magnesium-wordcloud-panel && \
grafana-cli plugins install flant-statusmap-panel && \
grafana-cli plugins install grafana-piechart-panel && \
grafana-cli plugins install grafana-worldmap-panel

